### ISSUE TITLE
Make it official

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-rss-feed#1]
There's no reason each site should have to struggle with the best way to publish an RSS feed of their Jekyll posts, a problem that's been solved a million times over (but right now, is limited to copy/pasta from blog posts with no clear winner). 

There are lots of standards (RSS 1.0, RSS 2.0, Atom) to choose from, and lots of edge cases you shouldn't have to worry about. Similar to the sitemap plugin, we should figure out the "best" feed template, and distribute it as a set-it-and-forget-it plugin. See [this conversation](https://twitter.com/benbalter/status/598117861996032000) with @holman and @bkeepers for some context.

@parkr this is copied wholesale from jekyll-sitemap (swapping out `sitemap.xml` for `feed.xml`). If you're :+1: I'd like to transfer this over to the Jekyll org and get some feedback on the template with the goal of getting in on Pages (since it's really just `jekyll-sitemap` with a different template). 

FWIW, there's also an opportunity here to abstract 99% of this and `jekyll-sitemap` into one shared "plugin that injects a shared template" type plugin, but starting here, as this works.

Thoughts?

**Comment by parkr** [comment]
I'm in. Before something is released, can I tweet for some feedback?

**Comment by benbalter** [comment]
>  Before something is released, can I tweet for some feedback?

Yes please! This was literally 5 minutes of copy-pasta from jekyll-sitemap and my own RSS feed template (which was likely copied from a random blog post many moons ago). I'll transfer it to the jekyll org momentarily and any means that we have to get feedback, I'm sure it could use it. :smile:
